version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs

  backend:
    build: .
    ports:
      - '3001:3000'
      - '5555:5555'
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
